
name: 'spain_housing_dbt'
version: '1.0.0'
config-version: 2

profile: 'spain_housing_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  spain_housing_dbt:
    # Configuración global para los modelos
    staging:
      +materialized: view
      +schema: staging
    core:
      +materialized: table
      +schema: core
    marts:
      +materialized: table
      +schema: marts
